// SPDX-License-Identifier: GPL-3.0-or-later
'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const Refresh=require('../app/app-refresh.js');
const flush=async()=>{for(let i=0;i<12;i++)await Promise.resolve();};
function clock(){let t=10000,n=0;const jobs=new Map();return {now:()=>t,setTimeout(fn,ms){jobs.set(++n,{at:t+ms,fn});return n;},clearTimeout(id){jobs.delete(id);},async advance(ms){await flush();const end=t+ms;for(let runs=0;runs<10000;runs++){const next=[...jobs].sort((a,b)=>a[1].at-b[1].at)[0];if(!next||next[1].at>end)break;t=next[1].at;jobs.delete(next[0]);next[1].fn();await flush();}t=end;await flush();},jobs};}
function fixture(){const c=clock(),calls=[],applied=[];let allowed=true;const r=new Refresh({...c,canApply:()=>allowed,read:()=>{let resolve,reject;const p=new Promise((a,b)=>{resolve=a;reject=b;});const call={resolve,reject,cancelled:false};p.cancel=()=>{call.cancelled=true;};calls.push(call);return p;},apply:apps=>{applied.push(apps);return true;}});return {r,c,calls,applied,block:v=>{allowed=!v;}};}
const snap=()=>({preview:false,apps:[{id:'org.test.new',title:'New'}]});
test('startup/return burst coalesces to one read',async()=>{const f=fixture();f.r.resume();f.r.resume();f.r.resume();await f.c.advance(0);assert.equal(f.calls.length,1);f.r.resume();f.calls[0].resolve(snap());await f.c.advance(1);assert.equal(f.calls.length,1);assert.equal(f.applied.length,1);});
test('a new snapshot is read every 30 seconds only while active',async()=>{const f=fixture();f.r.resume();await f.c.advance(0);f.calls[0].resolve(snap());await f.c.advance(1);await f.c.advance(29998);assert.equal(f.calls.length,1);await f.c.advance(2);assert.equal(f.calls.length,2);f.r.pause();await f.c.advance(120000);assert.equal(f.calls.length,2);assert.equal(f.c.jobs.size,0);});
test('hide cancels a native read and rejects its late success',async()=>{const f=fixture();f.r.resume();await f.c.advance(0);f.r.pause();assert.equal(f.calls[0].cancelled,true);f.calls[0].resolve(snap());await f.c.advance(100);assert.equal(f.applied.length,0);});
test('resume requests fresh data after a hidden in-flight read',async()=>{const f=fixture();f.r.resume();await f.c.advance(0);f.r.pause();await f.c.advance(5000);f.r.resume();await f.c.advance(0);f.calls[0].resolve(snap());f.calls[1].resolve(snap());await f.c.advance(1);assert.equal(f.applied.length,1);});
test('hold/dialog/navigation blocks requests and reconciliation until idle',async()=>{const f=fixture();f.block(true);f.r.resume();await f.c.advance(1000);assert.equal(f.calls.length,0);f.block(false);await f.c.advance(500);assert.equal(f.calls.length,1);f.block(true);f.calls[0].resolve(snap());await f.c.advance(3000);assert.equal(f.applied.length,0);assert.equal(f.r.getState().pending,true);f.block(false);await f.c.advance(500);assert.equal(f.applied.length,1);});
test('failed or malformed list never calls apply with an empty replacement',async()=>{for(const reply of [null,{}, {apps:{}},{apps:Array(1001).fill({})}]){const f=fixture();f.r.resume();await f.c.advance(0);f.calls[0].resolve(reply);await f.c.advance(1);assert.equal(f.applied.length,0);assert.ok(f.r.error);}});
test('permission failure keeps state and retries on normal bounded cadence',async()=>{const f=fixture();f.r.resume();await f.c.advance(0);f.calls[0].reject(Error('permission denied'));await f.c.advance(1);assert.match(f.r.error,/permission/);await f.c.advance(29998);assert.equal(f.calls.length,1);await f.c.advance(2);assert.equal(f.calls.length,2);});
test('preview never erases visible catalogue',async()=>{const f=fixture();f.r.resume();await f.c.advance(0);f.calls[0].resolve({preview:true,apps:[]});await f.c.advance(1);assert.equal(f.applied.length,0);assert.equal(f.r.error,null);});
test('invalidate discards an old response and pending data after uninstall',async()=>{const f=fixture();f.r.resume();await f.c.advance(0);f.r.invalidate();f.calls[0].resolve(snap());await f.c.advance(2000);assert.equal(f.applied.length,0);assert.equal(f.calls.length,2);f.calls[1].resolve({apps:[]});await f.c.advance(1);assert.deepEqual(f.applied,[[]]);});
test('manual refresh is immediate once safe but rate limited across repeated Home presses',async()=>{const f=fixture();f.r.resume();await f.c.advance(0);f.calls[0].resolve(snap());await f.c.advance(1);f.r.refresh();await f.c.advance(100);assert.equal(f.calls.length,1);await f.c.advance(1900);assert.equal(f.calls.length,2);});
test('destroy cancels work, is idempotent and cannot be resumed',async()=>{const f=fixture();f.r.resume();await f.c.advance(0);f.r.destroy();f.r.destroy();f.r.resume();f.calls[0].resolve(snap());await f.c.advance(60000);assert.equal(f.c.jobs.size,0);assert.equal(f.calls.length,1);assert.equal(f.applied.length,0);});
test('synchronous read and apply errors cannot break the Home controller',async()=>{const f=fixture();f.r.options.read=()=>{throw Error('offline');};f.r.resume();await f.c.advance(0);assert.equal(f.r.error,'offline');f.r.options.read=()=>Promise.resolve(snap());f.r.options.apply=()=>{throw Error('invalid data');};await f.c.advance(30001);assert.equal(f.r.error,'invalid data');});
test('listApps propagates cancellation and does not accept a truncated >1000-entry list',async()=>{
 const requests=[],timers=new Map();const root={location:{protocol:'file:',search:''},navigator:{userAgent:'webOS SmartTV'},PalmSystem:{identifier:'com.webos.app.home'},setTimeout(fn){timers.set(timers.size+1,fn);return timers.size;},clearTimeout(i){timers.delete(i);}};
 root.PalmServiceBridge=function(){this.cancel=()=>{this.cancelled=true;};this.call=(uri,payload)=>requests.push({uri,payload:JSON.parse(payload),bridge:this});};
 vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../app/tv-bridge.js'),'utf8'),{window:root,console});
 let p=root.C5TV.listApps();assert.equal(typeof p.cancel,'function');p.cancel();await assert.rejects(p,/cancelled/);assert.equal(requests[0].bridge.cancelled,true);
 p=root.C5TV.listApps();requests[1].bridge.onservicecallback(JSON.stringify({returnValue:true,apps:Array(1001).fill({id:'x',visible:true})}));await assert.rejects(p,/application list/);
});
