// SPDX-License-Identifier: GPL-3.0-or-later
'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const Hold=require('../app/hold-gesture.js'),Order=require('../app/menu-order.js');
const managerSource=fs.readFileSync(path.join(__dirname,'../app/app-manager.js'),'utf8');
function clock(){let now=0,n=0;const jobs=new Map();return {setTimeout(fn,ms){jobs.set(++n,{fn,at:now+ms});return n;},clearTimeout(id){jobs.delete(id);},advance(ms){now+=ms;for(const[id,j]of jobs)if(j.at<=now){jobs.delete(id);j.fn();}},jobs};}
function manager(){const c=clock(),calls=[],root={C5TV:{isTV:()=>true},PalmSystem:{identifier:'com.webos.app.home'},setTimeout:c.setTimeout,clearTimeout:c.clearTimeout};root.PalmServiceBridge=function(){this.cancel=()=>{this.cancelled=true;};this.call=(uri,data)=>calls.push({uri,data:JSON.parse(data),reply:r=>this.onservicecallback(JSON.stringify(r)),bridge:this});};const sandbox={window:root,console};vm.runInNewContext(managerSource,sandbox);return {api:root.LGXMBAppManager,calls,c,root};}
const info=(id='org.test.app',kind='developer',extra={})=>({id,title:'Test app',version:'1.2.3',vendor:'Example',type:'web',removable:true,systemApp:false,folderPath:'/media/'+(kind==='developer'?'developer':'cryptofs')+'/apps/usr/palm/applications/'+id,...extra});
const flush=async()=>{for(let i=0;i<8;i++)await Promise.resolve();};
function storage(){const data={};return{getItem:k=>data[k]||null,setItem:(k,v)=>{data[k]=v;},data};}

test('short OK fires once on release, never on keydown',()=>{const c=clock(),h=new Hold(c),events=[];h.down('key',()=>events.push('tap'),()=>events.push('hold'));assert.deepEqual(events,[]);c.advance(400);h.up('key');h.up('key');c.advance(1000);assert.deepEqual(events,['tap']);});
test('650 ms hold consumes all repeats and release',()=>{const c=clock(),h=new Hold(c),events=[];h.down('key',()=>events.push('tap'),()=>events.push('hold'));c.advance(649);assert.deepEqual(events,[]);c.advance(1);for(let i=0;i<20;i++)assert.equal(h.down('key',()=>events.push('bad'),()=>{}),false);h.up('key');assert.deepEqual(events,['hold']);});
test('cancelled or stale hold cannot open options or launch',()=>{const c=clock(),h=new Hold(c);let n=0;h.down('key',()=>n++,()=>n++);const callback=[...c.jobs.values()][0].fn;h.cancel();callback();h.up('key');assert.equal(n,0);});
test('wrong pointer/key release does not complete another gesture',()=>{const c=clock(),h=new Hold(c);let n=0;h.down('pointer',()=>n++,()=>n++);assert.equal(h.up('key'),false);h.up('pointer');assert.equal(n,1);});
test('sort preserves objects and selected identity with natural ordering',()=>{const c={id:'apps',items:[{id:'z',title:'Zebra'},{id:'10',title:'App 10'},{id:'2',title:'App 2'}]},original=c.items.slice(),s=storage(),o=new Order([c],s);assert.equal(o.set(c,'az','z'),2);assert.deepEqual(c.items.map(i=>i.id),['2','10','z']);assert.equal(c.items[2],original[0]);assert.equal(o.set(c,'default','z'),0);assert.deepEqual(c.items,original);});
test('sort preference survives recreation; invalid saved modes are ignored',()=>{const s=storage(),c={id:'apps',items:[{id:'a',title:'A'},{id:'b',title:'B'}]};new Order([c],s).set(c,'za','a');assert.equal(new Order([c],s).modes.apps,'za');s.setItem('lg-xmb-menu-order-v1','{"apps":"recent","bogus":"az"}');assert.equal(new Order([c],s).modes.apps,'default');});
test('storage denial does not reorder the menu',()=>{const c={id:'apps',items:[{id:'b',title:'B'},{id:'a',title:'A'}]},s=storage(),o=new Order([c],s);s.setItem=()=>{throw Error('denied');};assert.throws(()=>o.set(c,'az','b'));assert.deepEqual(c.items.map(i=>i.id),['b','a']);});
test('deletion removes duplicate shortcuts and preserves other selections',()=>{const c=[{id:'music',title:'Music',items:[{id:'plex',title:'Plex'},{id:'a',title:'A'}]},{id:'video',title:'Video',items:[{id:'plex',title:'Plex'}]}],sel=[1,0],o=new Order(c,storage());o.remove('plex',sel);assert.equal(c[0].items[sel[0]].id,'a');assert.equal(c[1].items[sel[1]].action,'empty');assert.ok(o.removed.has('plex'));});
test('confirmed deleted shortcuts persist and return after verified reinstall',()=>{const s=storage(),fresh=()=>[{id:'video',title:'Video',items:[{id:'plex',title:'Plex'}]}],a=fresh(),o=new Order(a,s);o.remove('plex',[0]);const b=fresh(),n=new Order(b,s);n.removed.forEach(id=>n.remove(id,[0]));assert.equal(b[0].items[0].action,'empty');n.reconcile([{id:'plex'}]);assert.equal(b[0].items[0].id,'plex');assert.equal(n.removed.size,0);});
test('protect launcher, Homebrew recovery and all system app identifiers',()=>{const {api}=manager();for(const id of ['com.webos.app.home','com.webos.app.hdmi1','org.local.openxmb.c5','org.webosbrew.hbchannel','org.webosbrew.hbchannel.service','com.palm.app.settings','com.palmdts.devmode'])assert.equal(api.normalize(info(id),id).removable,false,id);});
test('unknown path, absent permission, system flag and traversal fail closed',()=>{const {api}=manager();for(const e of [{removable:undefined},{removable:'true'},{systemApp:true},{folderPath:'/usr/palm/applications/org.test.app'},{folderPath:'/media/developer/apps/usr/palm/applications/../org.test.app'},{folderPath:undefined}])assert.equal(api.normalize(info('org.test.app','developer',e),'org.test.app').removable,false);});
test('metadata is matched to requested id and sanitized',()=>{const {api}=manager();assert.throws(()=>api.normalize(info(),'org.other'));assert.equal(api.normalize(info('org.test.app','developer',{title:'Hi\u202e\u0000there'}),'org.test.app').title,'Hithere');});
test('delete requires explicit confirmation and sends no calls for protected apps',async()=>{const {api,calls}=manager();await assert.rejects(api.removeApp('org.test.app',false));await assert.rejects(api.removeApp('org.webosbrew.hbchannel',true));assert.equal(calls.length,0);});
test('developer uninstall waits through acknowledgement and status 21 until 31',async()=>{const {api,calls}=manager();let done=false;const p=api.removeApp('org.test.app',true).then(r=>{done=true;return r;});assert.equal(calls.length,1);assert.ok(calls[0].uri.endsWith('/getAppInfo'));calls[0].reply({returnValue:true,appInfo:info()});await flush();assert.equal(calls[1].uri,'luna://com.webos.appInstallService/dev/remove');assert.deepEqual(calls[1].data,{id:'org.test.app',subscribe:true});calls[1].reply({returnValue:true,subscribed:true});calls[1].reply({id:'org.test.app',statusValue:21});await flush();assert.equal(done,false);calls[1].reply({id:'org.test.app',statusValue:31});assert.equal((await p).id,'org.test.app');assert.equal(calls[1].bridge.cancelled,true);});
test('store app uses normal remove endpoint, not developer endpoint',async()=>{const {api,calls}=manager();const p=api.removeApp('cdp-30',true);calls[0].reply({returnValue:true,appInfo:info('cdp-30','store')});await flush();assert.equal(calls[1].uri,'luna://com.webos.appInstallService/remove');calls[1].reply({id:'cdp-30',statusValue:31});await p;});
test('late metadata after cancellation cannot dispatch removal',async()=>{const {api,calls}=manager();const p=api.removeApp('org.test.app',true),caught=assert.rejects(p,e=>e.code==='CANCELLED');p.cancelBeforeDispatch();calls[0].reply({returnValue:true,appInfo:info()});await caught;assert.equal(calls.length,1);});
test('cancelling panel after dispatch does not claim the uninstall was undone',async()=>{const {api,calls}=manager();const p=api.removeApp('org.test.app',true);calls[0].reply({returnValue:true,appInfo:info()});await flush();p.cancelBeforeDispatch();assert.equal(p.wasDispatched(),true);calls[1].reply({id:'org.test.app',statusValue:31});assert.equal((await p).ok,true);});
test('changed removability on fresh read prevents deletion',async()=>{const {api,calls}=manager();const p=api.removeApp('org.test.app',true);calls[0].reply({returnValue:true,appInfo:info('org.test.app','developer',{removable:false})});await assert.rejects(p,e=>e.code==='PROTECTED_APP');assert.equal(calls.length,1);});
test('concurrent removal is rejected and error status is not a success',async()=>{const {api,calls}=manager();const p=api.removeApp('org.test.app',true);await assert.rejects(api.removeApp('org.test.app',true),e=>e.code==='REMOVE_PENDING');calls[0].reply({returnValue:true,appInfo:info()});await flush();calls[1].reply({id:'org.test.app',statusValue:25,details:{reason:'App locked'}});await assert.rejects(p,/App locked/);assert.equal(calls.length,2);});
test('wrong-id terminal notification cannot remove current item',async()=>{const {api,calls}=manager();const p=api.removeApp('org.test.app',true);calls[0].reply({returnValue:true,appInfo:info()});await flush();calls[1].reply({id:'org.other',statusValue:31});await assert.rejects(p,e=>e.code==='INVALID_RESPONSE');});
test('uninstall timeout remains uncertain and never retries automatically',async()=>{const {api,calls,c}=manager();const p=api.removeApp('org.test.app',true);calls[0].reply({returnValue:true,appInfo:info()});await flush();c.advance(45000);await assert.rejects(p,e=>e.code==='TIMEOUT'&&/may still finish/.test(e.message));assert.equal(calls.length,2);});
test('preview metadata cannot enable or simulate successful deletion',async()=>{const {api,calls,root}=manager();root.C5TV.isTV=()=>false;assert.equal((await api.getAppInfo('org.test.app')).info.removable,false);await assert.rejects(api.removeApp('org.test.app',true),e=>e.code==='PREVIEW_ONLY');assert.equal(calls.length,0);});
