// SPDX-License-Identifier: GPL-3.0-or-later
'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../app/system-time.js'),'utf8'), model=require('../app/system-time.js');
function harness(tv=true){let next=0;const calls=[],timers=new Map(),root={C5TV:{isTV:()=>tv},setTimeout:(fn)=>{timers.set(++next,fn);return next;},clearTimeout:id=>timers.delete(id)};root.PalmServiceBridge=function(){this.cancel=()=>{this.cancelled=true;};this.call=(uri,payload)=>calls.push({uri,payload:JSON.parse(payload),bridge:this,reply:r=>this.onservicecallback(typeof r==='string'?r:JSON.stringify(r))});};vm.runInNewContext(source,{window:root,Intl,Date,Number,console});return{api:root.LGXMBSystemTime,calls,timers,root};}
const fields=(year,month,day,hour=12,minute=0,second=0)=>({year,month,day,hour,minute,second});
test('explicit write uses supplied endpoint and integer Unix seconds',async()=>{const h=harness(),p=h.api.set(1789735378);assert.equal(h.calls.length,1);assert.deepEqual(h.calls[0].payload,{utc:1789735378});assert.equal(h.calls[0].uri,'luna://com.webos.service.systemservice/time/setSystemTime');h.calls[0].reply({returnValue:true});assert.equal((await p).utc,1789735378);assert.equal(h.calls[0].bridge.cancelled,true);assert.equal(h.timers.size,0);});
test('reject milliseconds, fractional/string/NaN/out-of-range values without calls',async()=>{const h=harness();for(const value of [1789735378000,1789735378.5,'1789735378',NaN,Infinity,-1,4102444800])await assert.rejects(h.api.set(value),e=>e.code==='INVALID_TIME');assert.equal(h.calls.length,0);});
test('parallel Apply cannot dispatch two writes',async()=>{const h=harness(),p=h.api.set(1789735378);await assert.rejects(h.api.set(1789735379),e=>e.code==='TIME_PENDING');assert.equal(h.calls.length,1);h.calls[0].reply({returnValue:true});await p;});
test('permission denial stays independent and never calls exec or retries',async()=>{const h=harness(),p=h.api.set(1789735378);h.calls[0].reply({returnValue:false,errorText:'Permission denied',errorCode:-1});await assert.rejects(p,/Permission denied/);assert.equal(h.calls.length,1);});
test('write timeout is uncertain and never retries',async()=>{const h=harness(),p=h.api.set(1789735378);[...h.timers.values()][0]();await assert.rejects(p,e=>e.code==='TIMEOUT'&&/may have applied/.test(e.message));assert.equal(h.calls.length,1);});
test('read is one-shot and normalizes native timezone not host timezone',async()=>{const h=harness(),p=h.api.get();assert.deepEqual(h.calls[0].payload,{});h.calls[0].reply({returnValue:true,utc:1789735378,timezone:'Europe/Amsterdam'});const r=await p;assert.equal(r.local.hour,14);assert.equal(r.local.minute,42);assert.equal(r.local.second,58);assert.equal(r.timezone,'Europe/Amsterdam');});
test('cancelled read ignores late reply',async()=>{const h=harness(),p=h.api.get(),check=assert.rejects(p,e=>e.code==='CANCELLED');p.cancel();h.calls[0].reply({returnValue:true,utc:1789735378,timezone:'UTC'});await check;assert.equal(h.calls[0].bridge.cancelled,true);});
test('native bad timezone or mismatched unnamed offset is not guessed',async()=>{for(const data of [{timezone:'Not/AZone'},{offset:123}]){const h=harness(),p=h.api.get();h.calls[0].reply({returnValue:true,utc:1789735378,...data});await assert.rejects(p,e=>/TIMEZONE/.test(e.code));}});
test('malformed and oversized replies fail and clean up',async()=>{for(const reply of ['{bad',' '.repeat(16385),'[]']){const h=harness(),p=h.api.get();h.calls[0].reply(reply);await assert.rejects(p,e=>e.code==='INVALID_RESPONSE');assert.equal(h.timers.size,0);}});
test('desktop preview has no native write',async()=>{const h=harness(false);assert.equal((await h.api.set(1789735378)).preview,true);assert.equal((await h.api.get()).preview,true);assert.equal(h.calls.length,0);});
test('local/UTC conversion matches the user example in Amsterdam',()=>assert.deepEqual(model.candidates(fields(2026,9,18,14,42,58),'Europe/Amsterdam'),[1789735378]));
test('summer and winter use target-date DST not current offset',()=>{for(const month of [1,7]){const p=fields(2026,month,10);const utc=model.candidates(p,'Europe/Amsterdam')[0];assert.equal(new Date(utc*1000).getUTCHours(),month===1?11:10);assert.deepEqual(model.parts(utc,'Europe/Amsterdam'),p);}});
test('invalid calendar days and leap seconds cannot silently roll over',()=>{for(const p of [fields(2026,2,29),fields(2024,4,31),fields(2026,1,1,24),fields(2026,1,1,0,0,60)])assert.throws(()=>model.candidates(p,'UTC'),e=>e.code==='INVALID_DATE');assert.equal(model.days(2024,2),29);assert.equal(model.days(2026,2),28);});
test('DST spring gap is rejected; autumn ambiguity returns both choices',()=>{assert.throws(()=>model.candidates(fields(2026,3,29,2,30),'Europe/Amsterdam'),e=>e.code==='NONEXISTENT_TIME');const a=model.candidates(fields(2026,10,25,2,30),'Europe/Amsterdam');assert.equal(a.length,2);assert.equal(a[1]-a[0],3600);});
test('fractional timezone offsets round trip without one-hour assumptions',()=>{for(const zone of ['Asia/Kathmandu','Australia/Adelaide','America/St_Johns','Pacific/Chatham']){const p=fields(2026,6,18,7,12,45),u=model.candidates(p,zone);assert.equal(u.length,1);assert.deepEqual(model.parts(u[0],zone),p);}});
test('date row and modules load before app without manifest or preferences changes',()=>{const root=path.resolve(__dirname,'..'),html=fs.readFileSync(path.join(root,'app/index.html'),'utf8'),app=fs.readFileSync(path.join(root,'app/app.js'),'utf8');assert.ok(html.indexOf('system-time.js')<html.indexOf('date-time-settings.js'));assert.ok(html.indexOf('date-time-settings.js')<html.indexOf('src="app.js"'));assert.match(app,/'datetime'\].indexOf\(item.action\)/);assert.doesNotMatch(source,/luna-send|\/exec|setPreferences|setTimeWithNTP/);});
