/* OpenXMB C5 web adaptation, 2026. SPDX-License-Identifier: GPL-3.0-or-later */
(function(){'use strict';
var categories=window.C5Catalog, selectedCategory=1, selections=categories.map(function(){return 0;}), busy=false, modalOpen=false, lastDirection=0, toastTimer, announceTimer;
var preferences={theme:'midnight',motion:'full',sound:false,previewMode:'cached',waveSpeed:'normal',waveBrightness:'normal',backBehavior:'stay'};
var themes={midnight:{name:'Midnight',background:'#050911',wave:'#738acf',accent:'#a7baf3'},ocean:{name:'Ocean',background:'#030e13',wave:'#4da6ab',accent:'#98dfdf'},ember:{name:'Ember',background:'#130906',wave:'#ac6c45',accent:'#eebd96'},forest:{name:'Forest',background:'#040f0b',wave:'#579b7a',accent:'#b0d6bb'},amber:{name:'Amber',background:'#130f05',wave:'#c49a4a',accent:'#e0c998'},rose:{name:'Rose',background:'#13080d',wave:'#b86e8c',accent:'#e6b2c7'},violet:{name:'Violet',background:'#0d0816',wave:'#9678ca',accent:'#c8b5ec'},graphite:{name:'Graphite',background:'#090b0d',wave:'#83939d',accent:'#ccd4d9'},seasonal:{name:'Seasonal',background:'#080813',wave:'#2e2e73',accent:'#b3b3ea'}};
// Monthly colours are adapted from OpenXMB config.json, shell.theme-month-colours.
var monthColours=['#f2e6a6','#9e4540','#4da640','#f299cc','#99cc59','#b399e6','#80d9f2','#3373f2','#2e2e73','#994db3','#cc8040','#e64040'];
var $=function(id){return document.getElementById(id);};
try{var saved=JSON.parse(localStorage.getItem('openxmb-c5-preferences-v1')||'{}');if(Object.prototype.hasOwnProperty.call(themes,saved.theme))preferences.theme=saved.theme;if(saved.motion==='reduced'||saved.motion==='full')preferences.motion=saved.motion;else if(matchMedia('(prefers-reduced-motion: reduce)').matches)preferences.motion='reduced';preferences.sound=saved.sound===true;preferences.previewMode=saved.previewMode==='live'?'live':'cached';if(['slow','normal','fast'].indexOf(saved.waveSpeed)!==-1)preferences.waveSpeed=saved.waveSpeed;if(['low','normal','high'].indexOf(saved.waveBrightness)!==-1)preferences.waveBrightness=saved.waveBrightness;if(saved.backBehavior==='lg')preferences.backBehavior='lg';}catch(ignore){}
var wave=new C5Wave($('wave'),{quality:C5TV.isTV()?'720p':'1080p'});
var inputPreview=new C5InputPreview($('inputPreview'),{isTV:function(){return C5TV.isTV();}});
var thumbnail=new C5Thumbnail($('inputThumbnail'),$('thumbnailFallback'),{isTV:function(){return C5TV.isTV();}});
var detailItemId=null,launchGeneration=0,pageActive=!document.hidden,lastReturnAt=-Infinity;
document.querySelector('.input-preview-symbol').innerHTML=C5Icon('hdmi');
document.querySelector('.thumbnail-symbol').innerHTML=C5Icon('hdmi');
var audioContext, inputLabelRead=null;
function tick(){if(!preferences.sound||document.hidden)return;try{if(!audioContext)audioContext=new(window.AudioContext||window.webkitAudioContext)();if(audioContext.state==='suspended')audioContext.resume();var oscillator=audioContext.createOscillator(),gain=audioContext.createGain(),now=audioContext.currentTime;oscillator.type='sine';oscillator.frequency.setValueAtTime(660,now);oscillator.frequency.exponentialRampToValueAtTime(440,now+.065);gain.gain.setValueAtTime(.018,now);gain.gain.exponentialRampToValueAtTime(.0001,now+.065);oscillator.connect(gain);gain.connect(audioContext.destination);oscillator.start(now);oscillator.stop(now+.07);}catch(ignore){}}
function save(){try{localStorage.setItem('openxmb-c5-preferences-v1',JSON.stringify(preferences));}catch(ignore){toast('This device could not save your preference.');}}
function seasonal(){var colour=monthColours[new Date().getMonth()],rgb=colour.match(/[a-f0-9]{2}/gi).map(function(x){return parseInt(x,16);});themes.seasonal.wave=colour;themes.seasonal.background='#'+rgb.map(function(v){return Math.max(3,Math.round(v*.07)).toString(16).padStart(2,'0');}).join('');themes.seasonal.accent='#'+rgb.map(function(v){return Math.round(v*.45+255*.55).toString(16).padStart(2,'0');}).join('');}
function applyPreferences(){seasonal();var theme=themes[preferences.theme];document.documentElement.style.setProperty('--accent','#ffffff');document.documentElement.style.setProperty('--accent-rgb','255,255,255');document.documentElement.style.setProperty('--background',theme.background);document.documentElement.style.setProperty('--background-rgb',theme.background.match(/[a-f0-9]{2}/gi).map(function(x){return parseInt(x,16);}).join(','));document.body.classList.toggle('reduced-motion',preferences.motion==='reduced');wave.setTheme(theme);wave.setStyle({speed:{slow:0.5,normal:1.5,fast:2.25}[preferences.waveSpeed],brightness:{low:0.6,normal:1,high:1.5}[preferences.waveBrightness]});wave.setReducedMotion(preferences.motion==='reduced');}
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(function(){$('toast').classList.remove('show');},4200);}
function clearToast(){clearTimeout(toastTimer);$('toast').classList.remove('show');if($('toast').textContent)$('toast').textContent='';}
function invalidateLaunch(){launchGeneration++;busy=false;$('items').removeAttribute('aria-busy');}
function currentItem(){return categories[selectedCategory].items[selections[selectedCategory]];}
function currentPort(){var item=currentItem(),match=categories[selectedCategory].id==='inputs'&&item.action==='input'&&/^com\.webos\.app\.hdmi([1-4])$/.exec(item.id);return match?Number(match[1]):null;}
function stopInputPreview(){inputPreview.stop();$('previewPanel').classList.remove('live-preview');}
function syncInputPreview(){var port=currentPort(),shown=!!port&&!modalOpen,active=shown&&pageActive&&!document.hidden&&!busy,live=active&&preferences.previewMode==='live';document.querySelector('.detail').classList.toggle('has-input-preview',shown);$('previewPanel').hidden=!shown;$('previewPanel').classList.toggle('live-preview',live);$('previewButton').setAttribute('aria-label','Open '+currentItem().title+' full-screen');if(!active||live){thumbnail.setPaused(true);thumbnail.select(shown?port:null);}else{thumbnail.select(port);thumbnail.setPaused(false);}if(live)inputPreview.select(port);else inputPreview.stop();}
function renderDetailText(){
  var item=currentItem();
  // Labels can change while the selected physical input stays the same.
  if($('detailType').textContent!==item.type)$('detailType').textContent=item.type;
  if($('detailTitle').textContent!==item.title)$('detailTitle').textContent=item.title;
  if($('detailDescription').textContent!==item.description)$('detailDescription').textContent=item.description;
  if(detailItemId!==item.id){$('detailEmblem').innerHTML=C5Icon(item.icon);detailItemId=item.id;}
  $('previewButton').setAttribute('aria-label','Open '+item.title+' full-screen');
}
function renderDetail(){renderDetailText();syncInputPreview();}
function buildCategories(){var nav=$('categories');categories.forEach(function(cat,index){var b=document.createElement('button');b.className='category';b.setAttribute('aria-label',cat.title);b.innerHTML='<span class="category-icon">'+C5Icon(cat.icon)+'</span><span class="category-label"></span>';b.querySelector('.category-label').textContent=cat.title;b.addEventListener('click',function(){if(!busy){selectedCategory=index;buildItems();render();tick();}});nav.appendChild(b);});}
function buildItems(){var list=$('items');list.textContent='';list.setAttribute('aria-label',categories[selectedCategory].title);categories[selectedCategory].items.forEach(function(item,index){var b=document.createElement('button');b.className='item';b.id='item-'+index;b.setAttribute('role','option');b.tabIndex=-1;b.innerHTML='<span class="item-icon">'+C5Icon(item.icon)+'</span><span class="item-text"></span>';b.querySelector('.item-text').textContent=item.title;b.addEventListener('click',function(){if(busy)return;selections[selectedCategory]=index;render();tick();activate();});list.appendChild(b);});}
function render(){var cat=categories[selectedCategory],index=selections[selectedCategory],item=cat.items[index];[].forEach.call($('categories').children,function(button,i){var offset=i-selectedCategory;button.style.transform='translateX(calc(-50% + '+(offset*10.6)+'vw))';button.classList.toggle('active',offset===0);button.style.opacity=offset===0?'1':Math.abs(offset)>2?'.36':'.5';button.setAttribute('aria-current',offset===0?'true':'false');button.tabIndex=offset===0?0:-1;});[].forEach.call($('items').children,function(button,i){var offset=i-index;button.style.setProperty('--offset',offset);button.classList.toggle('selected',offset===0);button.setAttribute('aria-selected',offset===0?'true':'false');var visible=offset>=-1&&offset<=3;button.style.visibility=visible?'visible':'hidden';button.style.opacity=!visible?'0':offset===0?'1':offset===-1?'.38':String(.64-offset*.09);button.setAttribute('aria-hidden',visible?'false':'true');});$('items').setAttribute('aria-activedescendant','item-'+index);renderDetail();announceSelection();}
function announceSelection(){
  var cat=categories[selectedCategory],index=selections[selectedCategory],item=cat.items[index];
  clearTimeout(announceTimer);
  announceTimer=setTimeout(function(){
    $('selectionLive').textContent=cat.title+', '+item.title+', '+(index+1)+' of '+cat.items.length;
  },180);
}
function navigate(direction){if(busy)return;var next;if(direction==='left'||direction==='right'){next=Math.max(0,Math.min(categories.length-1,selectedCategory+(direction==='right'?1:-1)));if(next===selectedCategory){renderDetail();return;}selectedCategory=next;buildItems();}else{next=Math.max(0,Math.min(categories[selectedCategory].items.length-1,selections[selectedCategory]+(direction==='down'?1:-1)));if(next===selections[selectedCategory]){renderDetail();return;}selections[selectedCategory]=next;}render();tick();}
function row(label,colour,isSelected,handler,parent){var button=document.createElement('button');button.className='option';button.setAttribute('aria-pressed',String(isSelected));var labelSpan=document.createElement('span');if(colour){var swatch=document.createElement('i');swatch.className='swatch';swatch.style.background=colour;labelSpan.appendChild(swatch);}labelSpan.appendChild(document.createTextNode(label));button.appendChild(labelSpan);var mark=document.createElement('span');mark.className='option-check';mark.setAttribute('aria-hidden','true');mark.textContent=isSelected?'✓':'';button.appendChild(mark);button.addEventListener('click',handler);(parent||$('modalContent')).appendChild(button);return button;}
function selectChoice(parent,value){[].forEach.call(parent.querySelectorAll('[data-choice]'),function(button){var chosen=button.getAttribute('data-choice')===value;button.setAttribute('aria-pressed',String(chosen));button.querySelector('.option-check').textContent=chosen?'✓':'';});}
function choiceGroup(label,choices,value,handler){var group=document.createElement('section');group.className='choice-group';group.setAttribute('role','group');group.setAttribute('aria-label',label);var title=document.createElement('h3');title.textContent=label;group.appendChild(title);var options=document.createElement('div');options.className='choice-options';group.appendChild(options);choices.forEach(function(choice){var button=row(choice[1],null,value===choice[0],function(){handler(choice[0]);selectChoice(options,choice[0]);},options);button.setAttribute('data-choice',choice[0]);});$('modalContent').appendChild(group);return group;}
var modalType='';
function openModal(type){if(!modalOpen||modalType!==type)clearToast();if(modalType==='background')C5BackgroundSettings.close();if(modalType==='remote')C5RemoteSettings.close();if(modalType==='helper')C5HelperSettings.close();stopInputPreview();modalType=type;$('modal').classList.toggle('background-settings',type==='background');$('modal').classList.toggle('waves-settings',type==='motion');$('modal').classList.toggle('appearance-settings',type==='appearance');modalOpen=true;syncInputPreview();document.querySelector('.screen').setAttribute('aria-hidden','true');$('modalBackdrop').hidden=false;$('modalContent').textContent='';$('modalContent').classList.remove('theme-options');$('modalTitle').textContent={appearance:'Appearance',motion:'Waves',sound:'Navigation sound',previews:'Input previews',background:'Background activity',remote:'Remote buttons',helper:'TV integration',about:'About this menu'}[type];$('modalIntro').textContent={appearance:'',motion:'',sound:'',previews:'Live previews can change HDR mode.',background:'Choose what Home keeps closed. Apps can still be opened and close again when you return.',remote:'Home applies across the TV. Back applies in this menu.',helper:'',about:'Version 0.1.11'}[type];
if(type==='appearance'){$('modalContent').classList.add('theme-options');Object.keys(themes).forEach(function(key){var button=row(themes[key].name,key==='seasonal'?monthColours[new Date().getMonth()]:themes[key].wave,preferences.theme===key,function(){preferences.theme=key;applyPreferences();save();selectChoice($('modalContent'),key);});button.setAttribute('data-choice',key);});}
else if(type==='motion'){choiceGroup('Animation',[['full','On'],['reduced','Off']],preferences.motion,function(value){preferences.motion=value;applyPreferences();save();});choiceGroup('Speed',[['slow','Slow'],['normal','Normal'],['fast','Fast']],preferences.waveSpeed,function(value){preferences.waveSpeed=value;applyPreferences();save();});choiceGroup('Brightness',[['low','Low'],['normal','Normal'],['high','High']],preferences.waveBrightness,function(value){preferences.waveBrightness=value;applyPreferences();save();});}
else if(type==='sound'){row('Off',null,!preferences.sound,function(){preferences.sound=false;save();openModal(type);});row('On',null,preferences.sound,function(){preferences.sound=true;save();tick();openModal(type);});}
else if(type==='previews'){row('Set up TV features',null,false,function(){openModal('helper');});row('Cached',null,preferences.previewMode==='cached',function(){preferences.previewMode='cached';save();openModal(type);});row('Live',null,preferences.previewMode==='live',function(){preferences.previewMode='live';save();openModal(type);});}
else if(type==='helper'){C5HelperSettings.open();}
else if(type==='background'){C5BackgroundSettings.open();}
else if(type==='remote'){C5RemoteSettings.open({setup:function(){openModal('helper');},getBack:function(){return preferences.backBehavior;},setBack:function(value){if(['stay','lg'].indexOf(value)===-1)throw new Error('Choose a valid Back button setting.');var next=Object.assign({},preferences,{backBehavior:value});try{localStorage.setItem('openxmb-c5-preferences-v1',JSON.stringify(next));}catch(ignore){throw new Error('This device could not save the Back button setting.');}preferences.backBehavior=value;}});}
else{$('modalContent').innerHTML='<div class="about-copy"><p>A webOS adaptation of phenom64/OpenXMB. Wave mathematics and seasonal colours come from the original project, by Syndromatic and contributors.</p><p>This launcher adds no advertising or usage logging. Your TV and the apps you open retain their own privacy settings.</p><p>GPL version 3. Full source and licence notices accompany this app.</p></div>';}
var chosen=$('modalContent').querySelector('[aria-pressed="true"]')||$('modalContent').querySelector('button')||$('closeModal');chosen.focus();}
function closeModal(){if(modalType==='background')C5BackgroundSettings.close();if(modalType==='remote')C5RemoteSettings.close();if(modalType==='helper')C5HelperSettings.close();modalOpen=false;$('modalBackdrop').hidden=true;document.querySelector('.screen').removeAttribute('aria-hidden');$('items').focus();renderDetail();}
function modalKey(event){if(event.key==='Escape'||event.key==='Backspace'||event.keyCode===461){event.preventDefault();closeModal();return;}var group=document.activeElement.closest&&document.activeElement.closest('.choice-group');if(group&&/^Arrow/.test(event.key)){event.preventDefault();var horizontal=event.key==='ArrowLeft'||event.key==='ArrowRight',choices=Array.from(group.querySelectorAll('button')),groups=Array.from($('modalContent').querySelectorAll('.choice-group'));if(horizontal){var offset=event.key==='ArrowRight'?1:-1;choices[(choices.indexOf(document.activeElement)+offset+choices.length)%choices.length].focus();}else{var target=groups[groups.indexOf(group)+(event.key==='ArrowDown'?1:-1)];if(target)(target.querySelector('[aria-pressed="true"]')||target.querySelector('button')).focus();else $('closeModal').focus();}tick();return;}var controls=Array.from($('modal').querySelectorAll('button')),index=controls.indexOf(document.activeElement),delta=event.key==='ArrowDown'||event.key==='ArrowRight'?1:event.key==='ArrowUp'||event.key==='ArrowLeft'?-1:0;if(event.key==='Tab')delta=event.shiftKey?-1:1;if(delta){event.preventDefault();controls[(Math.max(index,0)+delta+controls.length)%controls.length].focus();tick();}}
async function activate(){if(busy||!pageActive||document.hidden)return;var item=currentItem();if(['appearance','motion','sound','previews','background','remote','helper','about'].indexOf(item.action)!==-1){openModal(item.action);return;}var generation=++launchGeneration;clearToast();busy=true;syncInputPreview();var launched=false;$('items').setAttribute('aria-busy','true');try{if(window.C5ProcessControl){try{await C5ProcessControl.prepareLaunch(item.id);}catch(ignore){}if(generation!==launchGeneration||!pageActive||document.hidden)return;}var result=item.action==='stock'?await C5TV.exitToStockHome():item.action==='input'?await C5TV.openInput(item.id):await C5TV.launch(item.id);if(generation!==launchGeneration||!pageActive||document.hidden)return;launched=!result.preview;if(result.preview)toast('Preview · '+item.title+' opens on your TV.');}catch(error){if(generation===launchGeneration&&pageActive&&!document.hidden)toast('Could not open '+item.title+'. '+(error.message||'Please try LG Home.'));}finally{if(generation===launchGeneration){busy=false;$('items').removeAttribute('aria-busy');if(!launched&&pageActive&&!document.hidden){renderDetail();$('items').focus();}}}}
function back(){if(modalOpen){closeModal();return;}if(preferences.backBehavior!=='lg'||busy||!pageActive||document.hidden)return;var generation=++launchGeneration;C5TV.platformBack().catch(function(error){if(generation===launchGeneration&&pageActive&&!document.hidden)toast(error.message||'Could not open the TV exit prompt.');});}
document.addEventListener('keydown',function(event){var isActivate=event.key==='Enter'||event.keyCode===13,isBack=event.key==='Escape'||event.key==='Backspace'||event.keyCode===461;if(event.repeat&&(isActivate||isBack)){event.preventDefault();return;}if(modalOpen){modalKey(event);return;}var direction={ArrowLeft:'left',ArrowRight:'right',ArrowUp:'up',ArrowDown:'down'}[event.key];if(direction){event.preventDefault();var now=performance.now();if(event.repeat&&now-lastDirection<100)return;lastDirection=now;navigate(direction);$('items').focus();}else if(isActivate){event.preventDefault();activate();}else if(isBack){event.preventDefault();back();}});
document.addEventListener('wheel',function(event){if(modalOpen){if($('modal').contains(event.target))return;event.preventDefault();return;}event.preventDefault();if(busy||Math.abs(event.deltaY)<2)return;var now=performance.now();if(now-lastDirection<130)return;lastDirection=now;navigate(event.deltaY>0?'down':'up');},{passive:false});
$('closeModal').addEventListener('click',closeModal);$('modalBackdrop').addEventListener('click',function(event){if(event.target===$('modalBackdrop'))closeModal();});
$('previewButton').addEventListener('click',function(){if(busy||modalOpen)return;activate();});
function updateClock(){var now=new Date(),time=now.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',hour12:false}),date=now.toLocaleDateString('en-GB',{weekday:'short',day:'2-digit',month:'short'});if($('time').textContent!==time){$('time').textContent=time;$('time').dateTime=now.toISOString();}if($('date').textContent!==date)$('date').textContent=date;}
function restoreFocus(){if(modalOpen){if(!$('modal').contains(document.activeElement)){var control=$('modalContent').querySelector('[aria-pressed="true"]')||$('modalContent').querySelector('button')||$('closeModal');control.focus();}}else if(document.activeElement!==$('items'))$('items').focus();}
async function refreshInputLabels(){
  if(!pageActive||document.hidden||inputLabelRead)return;
  var read;
  try{
    read=C5TV.listInputLabels();
    inputLabelRead=read;
    var result=await read;
    if(inputLabelRead!==read||!pageActive||document.hidden||result.preview)return;
    var inputCategory=categories.find(function(category){return category.id==='inputs';});
    var visible=categories[selectedCategory]===inputCategory, changed=false;
    inputCategory.items.forEach(function(item,index){
      var input=result.inputs.find(function(entry){return entry.id===item.id;});
      if(!input)return;
      var type=input.label==='HDMI '+input.port?'INPUT':'HDMI '+input.port;
      if(item.title===input.label&&item.type===type)return;
      item.title=input.label;
      item.type=type;
      changed=true;
      // Update text in place: keep row nodes, selection, focus and port bindings.
      if(visible)$('items').children[index].querySelector('.item-text').textContent=item.title;
    });
    if(visible&&changed){
      // Metadata must not restart media after a successful launch but before hide.
      renderDetailText();
      if(!modalOpen)announceSelection();
    }
  }catch(error){
    // Optional firmware API: keep defaults or the last successful names.
  }finally{
    if(inputLabelRead===read)inputLabelRead=null;
  }
}
function cancelInputLabels(){
  var read=inputLabelRead;
  inputLabelRead=null;
  if(read&&typeof read.cancel==='function'){
    try{read.cancel();}catch(ignore){}
  }
}
function restorePage(refreshStill){if(document.hidden)return;var now=performance.now(),wasActive=pageActive,before=thumbnail.getState();pageActive=true;wave.setPaused(false);renderDetail();if(refreshStill&&wasActive&&now-lastReturnAt>=250&&preferences.previewMode==='cached'&&before.port===currentPort()&&before.port!==null&&before.status!=='loading')thumbnail.refresh();lastReturnAt=now;updateClock();restoreFocus();if(!wasActive||refreshStill)refreshInputLabels();}
function suspendPage(){var wasActive=pageActive;pageActive=false;cancelInputLabels();invalidateLaunch();clearToast();clearTimeout(announceTimer);if(wasActive){stopInputPreview();thumbnail.setPaused(true);wave.setPaused(true);}}
function handleRelaunch(){invalidateLaunch();clearToast();if(modalOpen)closeModal();restorePage(true);}
// handlesRelaunch stays false: webOS brings the app forward automatically.
// A Home press while already visible still needs to leave any open dialog.
document.addEventListener('webOSRelaunch',handleRelaunch,true);
async function discoverApps(){try{var result=await C5TV.listApps();if(result.preview)return;var appCategory=categories.find(function(c){return c.id==='apps';}),known=new Set(categories.reduce(function(all,c){return all.concat(c.items.map(function(i){return i.id;}));},[]));result.apps.forEach(function(app){if(known.has(app.id)||app.id==='org.local.openxmb.c5')return;appCategory.items.push({id:app.id,title:app.title,icon:'apps',type:'ON YOUR TV',description:'Open '+app.title+'.',note:'Your app, with its existing settings.'});known.add(app.id);});if(categories[selectedCategory].id==='apps'){buildItems();render();}}catch(error){/* Curated, verified shortcuts remain usable if enumeration is not permitted. */}}
buildCategories();buildItems();applyPreferences();render();updateClock();var clockTimer=setInterval(updateClock,10000);$('items').focus();discoverApps();refreshInputLabels();
document.addEventListener('visibilitychange',function(){if(document.hidden){suspendPage();if(audioContext&&audioContext.state==='running')audioContext.suspend();}else restorePage(false);});
window.addEventListener('pagehide',suspendPage);window.addEventListener('pageshow',function(){restorePage(false);});window.addEventListener('beforeunload',function(){clearInterval(clockTimer);suspendPage();thumbnail.destroy();inputPreview.destroy();wave.destroy();});
window.C5App={getState:function(){return{category:categories[selectedCategory].id,item:currentItem().id,modal:modalOpen?modalType:null,remote:modalOpen&&modalType==='remote'?C5RemoteSettings.getState():null,preferences:Object.assign({},preferences),busy:busy,detailPending:false,detailItem:detailItemId,thumbnail:thumbnail.getState(),inputPreview:inputPreview.getState(),waveMode:wave.mode,waveError:wave.error||null,waveDiagnostics:wave.getDiagnostics()};}};
})();
