#!/usr/bin/env python3
"""Build CSP-compatible script strings from reviewable GLSL ES 3.00 sources."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
NAMES = ('fullscreenVertex', 'waveVertex', 'waveFragment', 'compositeFragment',
         'particleVertex', 'particleFragment', 'glareVertex', 'glareFragment',
         'monthlyBackground', 'backdropFragment')

def bundle():
    shaders = {}
    for name in NAMES:
        suffix = '.vert' if name.endswith('Vertex') else '.frag'
        source = (ROOT / 'shaders' / (name + suffix)).read_text(encoding='utf-8')
        if not source.startswith('#version 300 es\n'):
            raise ValueError(f'{name}: GLSL ES 3.00 must be the first line')
        shaders[name] = source
    return ('/* Generated by tools/bundle-ps3-shaders.py; edit shaders/* instead.\n'
            ' * lg-xmb contributors. GPL-3.0-or-later; FXAA section MIT, see notices. */\n'
            '(function (root) {\n  "use strict";\n  var shaders = ' + json.dumps(shaders, indent=2) + ';\n'
            '  if (typeof module === "object" && module.exports) module.exports = shaders;\n'
            '  else root.LGXMBPS3Shaders = Object.freeze(shaders);\n'
            '})(typeof window === "object" ? window : globalThis);\n')

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    path = ROOT / 'app' / 'ps3-native-shaders.js'
    output = bundle()
    if args.check:
        if not path.exists() or path.read_text(encoding='utf-8') != output:
            raise SystemExit('Shader bundle is stale; run tools/bundle-ps3-shaders.py')
        print('Shader bundle matches source.')
    else:
        path.write_text(output, encoding='utf-8')
